version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html
    links:
      - db
  db:
    image: mysql/mysql-server:8.0-amd64
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: Nick2020
      MYSQL_PASSWORD: Tinmothy
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db: